version: "3"
services:
  reverseproxy:
      image: klavenj/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: klavenj/udagram-user-api:prod
    environment:
      POSTGRESS_USERNAME: ${POSTGRESS_USERNAME}
      POSTGRESS_PASSWORD: ${POSTGRESS_PASSWORD}
      POSTGRESS_DB: ${POSTGRESS_DB}
      POSTGRESS_HOST: ${POSTGRESS_HOST}
      AWS_REGION: ${AWS_REGION}
      AWS_PROFILE: ${AWS_PROFILE}
      AWS_MEDIA_BUCKET: ${AWS_MEDIA_BUCKET}
      JWT_SECRET: ${JWT_SECRET}
      URL: "http://localhost:8100"
  backend-feed:
    image: klavenj/udagram-feed-api:prod
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: ${POSTGRESS_USERNAME}
      POSTGRESS_PASSWORD: ${POSTGRESS_PASSWORD}
      POSTGRESS_DB: ${POSTGRESS_DB}
      POSTGRESS_HOST: ${POSTGRESS_HOST}
      AWS_REGION: ${AWS_REGION}
      AWS_PROFILE: ${AWS_PROFILE}
      AWS_MEDIA_BUCKET: ${AWS_MEDIA_BUCKET}
      JWT_SECRET: ${JWT_SECRET}
      URL: "http://localhost:8100"
  frontend:
    image: klavenj/udagram-frontend:prod
    ports:
      - "8100:80"
